#!/usr/bin/env bash
#
# Open or refresh the weekly `nightly → main` Stable promotion PR.
#
# Invoked from .github/workflows/promotion.yml every Thursday and on manual
# workflow_dispatch. This script NEVER merges — the promote step (promote.sh)
# is what cuts the release; this only records what's queued. CLAUDE.md: `main`
# is the protected Stable branch and moves only via the nightly → main promotion,
# which cuts the Stable release; ci.yml's release job builds + publishes the DMG
# once the promotion lands on main.
#
# The PR body lists every squash-merged commit in `main..nightly` — the same set
# of PRs the upcoming Stable release will contain.
#
# Requires: gh, git. GH_TOKEN env var with `pull-requests: write` scope.
# Assumes the workspace is checked out at `nightly` with full history.

set -euo pipefail

# Which token are we using? GitHub's auto-issued GITHUB_TOKEN starts with
# `ghs_`; user PATs start with `ghp_` (classic) or `github_pat_` (fine-
# grained). We log the kind — NEVER the value — so a misconfigured
# PROMOTION_TOKEN secret is obvious in the run log instead of silently
# falling back to the blocked default token.
case "${GH_TOKEN:-}" in
  ghs_*)        echo "::warning::Using default GITHUB_TOKEN — the PROMOTION_TOKEN repo secret isn't set, so 'gh pr create' will fail unless Settings → Actions → General → 'Allow GitHub Actions to create and approve pull requests' is enabled." ;;
  ghp_*)        echo "Using classic PAT (PROMOTION_TOKEN)." ;;
  github_pat_*) echo "Using fine-grained PAT (PROMOTION_TOKEN)." ;;
  "")           echo "::error::GH_TOKEN is empty."; exit 1 ;;
  *)            echo "::warning::Using token of unknown shape — gh may reject it." ;;
esac

git fetch origin main:refs/remotes/origin/main --quiet

AHEAD=$(git rev-list --count origin/main..HEAD)
if [ "$AHEAD" -eq 0 ]; then
  echo "::notice::nightly is at main — nothing to promote."
  exit 0
fi
echo "$AHEAD commits ahead of main."

# How many squash-merged PRs are queued (subjects ending in "(#123)").
TOTAL=$(git log --format='%s' origin/main..HEAD | grep -cE '\(#[0-9]+\)$' || true)

TODAY=$(date -u +%Y-%m-%d)
BODY_FILE=$(mktemp)
{
  echo "## Stable promotion — week of ${TODAY}"
  echo
  echo "${TOTAL} PR$([ "$TOTAL" -eq 1 ] || echo s) queued from \`nightly\` since the last Stable cut."
  echo
  echo "**Don't use the merge button** — main and nightly don't share recent history, so squash/merge/rebase all conflict here. The release is cut by \`.github/scripts/promote.sh\` (run from this same workflow): it sets main to nightly's tree, pushes, and closes this PR. \`ci.yml\`'s release job then builds the DMG and publishes \`v0.<commit count on main>\` (the version never goes backwards — CLAUDE.md)."
  echo
  echo "### Queued changes"
  echo
  # Plain list of squash-merged PRs / commits in main..nightly.
  git log --format='- %s' origin/main..HEAD
  echo
  echo "---"
  echo "_Auto-generated by [\`.github/workflows/promotion.yml\`](.github/workflows/promotion.yml). Refreshes every Thursday 14:00 PKT (09:00 UTC) and on manual dispatch._"
} > "$BODY_FILE"

# Create/refresh via the REST API rather than `gh pr create` / `gh pr edit`.
# Those commands first run a GraphQL query that reads `repository.defaultBranchRef`,
# which a fine-grained PAT can't access without **Contents: Read** — so they fail
# with "Resource not accessible by personal access token" even when the token can
# write PRs. The REST pulls endpoint needs only **Pull requests: write**, so this
# keeps the required token scope minimal and the job robust.
REPO="${GITHUB_REPOSITORY:-rafay99-epic/porter}"

EXISTING=$(gh pr list --base main --head nightly --state open --json number --jq '.[0].number // empty')
if [ -n "$EXISTING" ]; then
  echo "::notice::Refreshing existing PR #${EXISTING}"
  gh api --method PATCH "repos/${REPO}/pulls/${EXISTING}" \
    -f body="$(cat "$BODY_FILE")" --silent
else
  echo "::notice::Opening new draft PR"
  gh api --method POST "repos/${REPO}/pulls" \
    -f title="Stable release · ${TODAY}" \
    -f head="nightly" -f base="main" \
    -F draft=true \
    -f body="$(cat "$BODY_FILE")" --jq '.number'
fi
